# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
      - id: check-ast

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--safe, --quiet]

  - repo: https://github.com/Pierre-Sassoulas/black-disable-checker
    rev: v1.1.0
    hooks:
      - id: black-disable-checker
