name: sample-factory
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - dbus=1.13.6
  - expat=2.2.9
  - ffmpeg=4.1.3
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.58.3
  - gmp=6.2.0
  - gnutls=3.6.5
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - icu=64.2
  - intel-openmp
  - jasper=1.900.1
  - jpeg=9c
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.10
  - mkl
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - nettle=3.4.1
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - opencv=4.1.0
  - openh264=1.8.0
  - openssl=1.1.1d
  - pcre=8.44
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.7.6
  - python_abi=3.7
  - pytorch=1.4.0
  - qt=5.9.7
  - readline=7.0
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.5.0
  - wheel=0.34.2
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - atari-py==0.2.6
    - cloudpickle==1.3.0
    - colorlog==4.1.0
    - cython==0.29.15
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.2.0
    - gputil==1.4.0
    - grpcio==1.27.2
    - gym==0.17.1
    - h5py==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - lockfile==0.12.2
    - lz4==3.0.2
    - markdown==3.2.1
    - opt-einsum==3.2.0
    - pandas==1.0.1
    - protobuf==3.11.3
    - psutil==5.7.0
    - pyglet==1.5.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - scipy==1.4.1
    - tensorboard==1.15.0
    - tensorboardx==2.0
    - termcolor==1.1.0
    - threadpoolctl==2.0.0
    - werkzeug==1.0.0
    - wrapt==1.12.1
