env: dmlab_benchmark
run: IMPALA
config:
    lr: 0.0001
    gamma: 0.99
    clip_rewards: False
    entropy_coeff: 0.0005
    train_batch_size: 2048
    sample_batch_size: 64
    num_sgd_iter: 1
    num_workers: 20
    num_envs_per_worker: 1
    num_cpus_per_worker: 0.5  # this allows to create 1 actor per core
    batch_mode: truncate_episodes
    observation_filter: NoFilter
    num_gpus: 1

    compress_observations: True  # enabling this didn't seem to improve throughput in this version of RLLIB

    num_data_loader_buffers: 1
    minibatch_buffer_size: 1
    replay_proportion: 0.0
    replay_buffer_num_slots: 0

    model:
        custom_model: vizdoom_vision_model
        conv_filters: [
            [32, [8, 8], 4],
            [64, [4, 4], 2],
            [128, [3, 3], 2],
        ]
        conv_activation: elu
        fcnet_activation: elu  # same as sample factory

        use_lstm: False
        framestack: False
        grayscale: False
        zero_mean: False

    env_config:
        res_w: 96
        res_h: 72
        renderer: software
        dmlab_throughput_benchmark: True
